#!/usr/bin/env bash


rules() {
	bspc rule -a '*:zathura' state=tiled
	bspc rule -a libreoffice state=tiled
	bspc rule -a soffice.bin state=tiled
}


defaults() {
	bspc config border_width         2
	bspc config window_gap          12

	bspc config split_ratio          0.52
	bspc config borderless_monocle   true
	bspc config gapless_monocle      true
}


multi_monitor_setup() {
	# Assumes we are plugged into a docking station with 2 connected display ports
	xrandr \
		--output eDP-1-1 --auto \
		--output DP-3.1 --auto --right-of eDP-1-1 \
		--output DP-3.2 --auto --right-of DP-3.1
	bspc monitor %eDP-1-1 -d 1 -a 4 -a 7
	bspc monitor %DP-3.1 -d 2 -a 5 -a 8
	bspc monitor %DP-3.2 -d 3 -a 6 -a 9
}


single_monitor_setup() {
	bspc monitor %eDP-1-1 -d 1 2 3 4 5 6
}


list_connected() {
	xrandr | grep " connected" | sed -e "s/\([A-Z0-9]\+\) connected.*/\1/"
}


main() {
	local connected
	connected="$(list_connected)"
	count="$(echo "$connected" | wc -l)"

	if [[ "$count" == "1" ]]; then
		single_monitor_setup
	else
		multi_monitor_setup
	fi

	defaults
	rules
}


main "$@"
