#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Vi mode
bindkey -v
export KEYTIMEOUT=1
bindkey '^R' history-incremental-pattern-search-backward

# Fzf
source $ZDOTDIR/.fzf

# Language environment
export LANG=en_GB.UTF-8

# ASDF
. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
   export EDITOR='vi'
else
   export EDITOR='nvim'
fi

# Python virtualenvwrapper
[ ! -d "$HOME/.virtualenvs" ] && mkdir "$HOME/.virtualenvs"
export WORKON_HOME="$HOME/.virtualenvs"
VENV="$(which virtualenvwrapper.sh)"
[[ ! -z $VENV ]] && source $VENV
